import { DataTypes } from 'sequelize';
import { sequelize } from '../config/sequelize.js';

const Barangays = sequelize.define(
  'Barangays',
  {
    ID: {
      type: DataTypes.BIGINT.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    barangayId: {
      type: DataTypes.STRING(50),
      unique: true,
      allowNull: false, // Auto-generated by MySQL trigger
    },
    provinceId: {
      type: DataTypes.BIGINT.UNSIGNED,
      allowNull: false,
      references: {
        model: 'provinces',
        key: 'ID',
      },
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
    },
    cityId: {
      type: DataTypes.BIGINT.UNSIGNED,
      allowNull: false,
      references: {
        model: 'cities',
        key: 'ID',
      },
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
    },
    barangayName: {
      type: DataTypes.STRING(50),
      allowNull: true,
    },
  },
  {
    tableName: 'barangays',
    timestamps: false,
  }
);

// Optional: Define associations for convenience
Barangays.associate = (models) => {
  Barangays.belongsTo(models.Provinces, {
    foreignKey: 'provinceId',
    as: 'province',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  });

  Barangays.belongsTo(models.Cities, {
    foreignKey: 'cityId',
    as: 'city',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  });
};

export default Barangays;