import { DataTypes } from "sequelize";
import { sequelize } from "../config/sequelize.js";

const Category = sequelize.define(
    'Category', 
    {
    ID: {
      type: DataTypes.BIGINT.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    categoryId: {
      type: DataTypes.STRING(50),
      allowNull: false, // it's auto-generated by MySQL
      unique: true,
    },
    categoryName: {
      type: DataTypes.STRING(100),
      allowNull: true,
    },
    createAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    updateAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    },
    {
      tableName: 'category',
      timestamps: false,
    }
)

export default Category;