import { DataTypes } from 'sequelize';
import { sequelize } from '../config/sequelize.js';

const Provinces = sequelize.define(
  'Provinces',
  {
    ID: {
      type: DataTypes.BIGINT.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    provinceId: {
      type: DataTypes.STRING(50),
      unique: true,
      allowNull: false, // it's auto-generated by MySQL
    },
    provinceName: {
      type: DataTypes.STRING(50),
      unique: true,
      allowNull: true,
    },
  },
  {
    tableName: 'provinces',
    timestamps: false, 
  }
);

export default Provinces;