import { DataTypes } from 'sequelize';
import { sequelize } from '../config/sequelize.js';

const Staff = sequelize.define(
  'Staff',
  {
    ID: {
      type: DataTypes.BIGINT.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    staffId: {
      type: DataTypes.STRING(50),
      unique: true,
      allowNull: false, // it's auto-generated by MySQL
    },
    firstName: {
      type: DataTypes.STRING(255),
      allowNull: false,
    },
    lastName: {
      type: DataTypes.STRING(255),
      allowNull: false,
    },
    emailAddress: {
      type: DataTypes.STRING(255),
      allowNull: true,
      unique: true,
    },
    phoneNumber: {
      type: DataTypes.STRING(15),
      allowNull: true,
      unique: true,
    },
    password: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
    createAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    updateAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    verifiedStaff: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
  },
  {
    tableName: 'staff',
    timestamps: false,
    validate: {
      emailOrPhoneOnly() {
        if (
          (this.emailAddress && this.phoneNumber) ||
          (!this.emailAddress && !this.phoneNumber)
        ) {
          throw new Error(
            'Either emailAddress or phoneNumber must be provided, but not both.'
          );
        }
      },
    },
  }
);

export default Staff;