import { DataTypes } from 'sequelize';
import { sequelize } from '../config/sequelize.js';

const SystemSettings = sequelize.define(
  'SystemSettings',
  {
    ID: {
      type: DataTypes.BIGINT.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    systemSettingsId: {
      type: DataTypes.STRING(50),
      allowNull: false, // Auto-generated by MySQL trigger
      unique: true,
    },
    businessName: {
      type: DataTypes.STRING(255),
      allowNull: false,
    },
    businessLogo: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    homeCoverImage: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    tableName: 'systemSettings',
    timestamps: false, // We're handling createdAt/updatedAt manually
  }
);

export default SystemSettings;