import { DataTypes } from 'sequelize';
import { sequelize } from '../config/sequelize.js';

const Variants = sequelize.define(
  'Variants',
  {
    ID: {
      type: DataTypes.BIGINT.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    variantId: {
      type: DataTypes.STRING(50),
      unique: true,
      allowNull: false, // Auto-generated by MySQL trigger (if you use one)
    },
    productId: {
      type: DataTypes.BIGINT.UNSIGNED,
      allowNull: false,
      references: {
        model: 'products', // This must match your actual products table name
        key: 'ID',
      },
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
    },
    variantName: {
      type: DataTypes.STRING(100),
      allowNull: false,
    },
    value: {
      type: DataTypes.STRING(50),
      allowNull: false,
    },
    createAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    updateAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    tableName: 'variants',
    timestamps: false,
  }
);

// Optional association for convenience
Variants.associate = function (models) {
  Variants.belongsTo(models.Products, {
    foreignKey: 'productId',
    as: 'product',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  });
};

export default Variants;