import { DataTypes } from "sequelize";
import { sequelize } from "../config/sequelize.js";

const VariantName = sequelize.define(
  "VariantName",
  {
    ID: {
      type: DataTypes.BIGINT.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    variantNameId: {
      type: DataTypes.STRING(50),
      allowNull: false, // Auto-generated by trigger in MySQL
      unique: true,
    },
    name: {
      type: DataTypes.STRING(100),
      allowNull: false,
    }
  },
  {
    tableName: "variantName",
    timestamps: false,
  }
);

export default VariantName;
